### ISSUE TITLE
OpenAPI::Client - how to pass additionalProperties in OpenAPI GET query request?

### ISSUE THREAD

**Issue by nige123** [jhthorsen/openapi-client#34]
I'm trying to pass filter variables in a GET request to an OpenAPI route with this specification:

 ```
 - in: query
    name: params
    schema:
      type: object
      additionalProperties:
        type: string
    style: form
    explode: true       
```
I've tried various different ways of passing the data at request time:
```

my $client = OpenAPI::Client->new(...);

my $tx = $client->findApps({
    params => { 'id' =>  '1' }
});

my $tx = $client->findApps({ 'id' =>  '1' });

```
What is the correct way to do this?

I'm currently getting this warning/error:

Use of uninitialized value $name in exists at /usr/local/share/perl/5.26.1/OpenAPI/Client.pm line 204
